### PR TITLE
Modify UG to fix documentation errors

### PR DESCRIPTION
**Pull request by twothicc**
Addresses #292, #281, #286 and #285
- Tag input is explained in detail under add and edit. (#285)
- Added Edit Command anchor link to table of contents. (#292) (#281)
- Added specifications under Edit Command description to indicate that prefix inputs for Edit is taken as a single value. Users should understand that `s/4000 5000` means an input of `4000 5000`, which does not adhere to the Add Input Specifications. (#286)
- Delete, Mark and Unmark inputs are specified to be unique.
- Shifted Prefix Inputs to its own sections with links returning to the command itself. Anchor links updated and tested.
- Added Markdown Styling to highlight certain "Do Nots" that would lead to an error.

### CODE REVIEW

**Review by kaushikkrdy — CHANGES_REQUESTED** [review]
Most changes make sense for greater understanding for the user! For the edit command, do you think it would make more sense to leave the links in for greater navigability for the reader? The old documentation provides a direct link to the specific category's prefix input specification, making it easier for user to navigate.

**Comment by twothicc** [comment]
Good suggestion. The old documentation has a lot of repeated text and reflects badly on our team's efforts. I can instead move the links into a table format so that I can remove the repeated text while still keeping it intuitive for the readers to navigate.

**Comment by twothicc** [comment]
- Links to specific input specifications have been provided in tables added below relevant commands in Feature section.
- These tables are wrapped in a markdown block to highlight them to the reader.
- Anchor Links are tested and working

**Comment by twothicc** [comment]
Also addresses #282 

- Added input specification anchor link for `done`, which is only unique to `find` command.
- Added clarification to `find` command to specify that not providing a prefix, or providing a prefix with empty input will both lead to no filtering of the applicants by that prefix. (#282)

**Pull request merged**
