### PR TITLE
Change `Add`, `Edit` and `Show` documentation in DG

### PR DESCRIPTION
**Pull request by twothicc**
Addresses #332 
- Changes to Activity Diagrams for `Add` and `Edit` to show `GUI` rather than `GUI Result Display`.
- Added `Show` command design considerations.
- Removed "more to be added" text.
- Fixed some text formatting.
- Fixed errors in `Show` sequence diagram.

### CODE REVIEW

**Review by kaushikkrdy — CHANGES_REQUESTED** [review]
Looks good except for a few minor things:

* Should we standardise across the board and just use `GUI` instead of Result Display and Person Panel (which is actually labelled as Applicant Panel in the UG)?
* I think we should standardise tense and not use past tense in the Activity Diagrams, so instead of updated, maybe we can use updates?

**Comment by twothicc** [comment]
Thank is a good suggestion. However, the part of the application that displays applicants is actually called PersonListPanel, so since this is a developer guide, I felt that it would make more sense to use the term "Person Panel".

There should not be a restriction on past or present tense for activity diagram. While standardizing may be make the activity diagram seem more consistent, it may make the wording awkward.

**Comment by kaushikkrdy** [comment]
I think Person Panel might still be confusing, as it is neither accurately represented as part of code, `PersonListPanel`and it's not represented as part of existing documentation, 'Applicant Panel'.  Perhaps a general GUI would be better to avoid bugs?

**Comment by twothicc** [comment]
Agreed. I forgot to make the changes to Edit command's activity diagram.

**Comment by kaushikkrdy** [comment]
LGTM!

**Pull request merged**
