### PR TITLE
Add intro to DG and change links and wording in UG

### PR DESCRIPTION
**Pull request by twothicc**
Addresses #357

### CODE REVIEW

**Comment by kaushikkrdy** [comment]
Looks good but perhaps one minor change: `table of contents` could be 'Redirect to table of contents' or 'Table of contents' to look nicer

**Review by kaushikkrdy — CHANGES_REQUESTED** [review]
Looks good but perhaps one minor change: table of contents could be 'Redirect to table of contents' or 'Table of contents' to look nicer

**Comment by twothicc** [comment]
Changed anchor links to `Table of contents`

**Comment by kaushikkrdy** [comment]
LGTM!

**Pull request merged**
